---
- name: "Run a module : nginx-centos"
  hosts: all, !local
  become: true
  roles:
#    - { role: nginx-centos, when: ansible_distribution == 'CentOS' }
#    - { role: nginx-ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: install-postgres-source }